// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerManager.Data;

#nullable disable

namespace ServerManager.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260316163346_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerManager.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RentedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServerStatus")
                        .HasColumnType("integer");

                    b.Property<int>("StorageGb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
